<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import TaskStepper from '../components/TaskStepper.vue'
import UndoPreview from '../components/UndoPreview.vue'
import { api, chooseDirectory, type ExecutionPlan, type Task } from '../services/api'
const route = useRoute(), task = ref<Task | null>(null), report = ref<Record<string, unknown> | null>(null), error = ref('')
const exportPath=ref(''),exporting=ref(false),exportResult=ref('')
const undoPlan=ref<ExecutionPlan|null>(null),ackUndo=ref(false),undoing=ref(false)
const undoAvailable=computed(()=>Boolean((report.value?.undo_summary as Record<string,unknown>|undefined)?.available))
async function load(){const id=String(route.params.id);[task.value,report.value]=await Promise.all([api.task(id),api.report(id)])}
onMounted(async () => { try { await load() } catch (e) { error.value = String(e) } })
async function exportAs(format:'json'|'csv') { if(!task.value)return; exporting.value=true;error.value='';try{const grant=await chooseDirectory('export',exportPath.value||undefined);if(grant.cancelled)return;const result=await api.exportReport(task.value.id,grant.grant_id!,format);exportResult.value=String(result.display_path)}catch(e){error.value=String(e)}finally{exporting.value=false} }
async function previewUndo(){if(!task.value||!report.value)return;const execution=report.value.execution_summary as Record<string,unknown>;if(!execution.plan_id||!execution.plan_hash)return;try{undoPlan.value=await api.compileUndo(task.value.id,task.value.revision,String(execution.plan_id),String(execution.plan_hash))}catch(e){error.value=String(e)}}
async function executeUndo(){if(undoing.value||!task.value||!undoPlan.value||!ackUndo.value)return;undoing.value=true;error.value='';try{const current=await api.task(task.value.id);task.value=current;await api.approvePlan(current.id,current.revision,undoPlan.value);await api.executePlan(current.id,current.revision,undoPlan.value);undoPlan.value=null;ackUndo.value=false;await load()}catch(e){error.value=String(e)}finally{undoing.value=false}}
</script>
<template><section class="page"><TaskStepper :current="5"/><p class="eyebrow">TASK REPORT</p><h1>{{task?.status==='COMPLETED_WITH_ISSUES'?'整理结束，仍有项目需要处理':'整理结果'}}</h1><p class="lead">报告计数来自操作日志；只读任务的已执行数始终为 0。</p><p v-if="error" class="notice danger-notice">{{error}}</p><div v-if="report" class="report-grid"><section class="state-card"><h2>扫描</h2><pre>{{JSON.stringify(report.scan_summary,null,2)}}</pre></section><section class="state-card"><h2>分类</h2><pre>{{JSON.stringify(report.classification_summary,null,2)}}</pre></section><section class="state-card"><h2>执行</h2><pre>{{JSON.stringify(report.execution_summary,null,2)}}</pre></section><section class="state-card"><h2>撤销范围</h2><pre>{{JSON.stringify(report.undo_summary,null,2)}}</pre></section></div><section v-if="undoAvailable" class="state-card"><h2>撤销已完成操作</h2><p>撤销会先生成独立反向计划；文件被外部修改或原位置被占用时保留现状并报告冲突。</p><button v-if="!undoPlan" class="secondary-button" @click="previewUndo">生成撤销预览</button><template v-else><UndoPreview :recoverable="undoPlan.operations.length" :modified="0" :occupied="0" :missing="0"/><div v-for="op in undoPlan.operations" :key="op.operation_id" class="operation-row"><code>{{op.source_path}}</code><b>→</b><code>{{op.target_path||'系统回收站'}}</code></div><p>反向计划 hash：<code>{{undoPlan.plan_hash}}</code></p><label class="ack"><input v-model="ackUndo" type="checkbox"/> 我已核对撤销目标与反向计划 hash</label><button class="primary-button" :disabled="!ackUndo||undoing" @click="executeUndo">{{undoing?'正在安全撤销…':'批准并执行撤销'}}</button></template></section><section class="state-card"><h2>导出可审计报告</h2><p>必须先授权导出目录；同名文件存在时不会覆盖。CSV 会转义公式前缀。</p><label>浏览器测试目录（桌面版可用原生选择器）<input v-model="exportPath" placeholder="仅显式开发模式需要填写" /></label><div class="button-row"><button class="secondary-button" :disabled="exporting" @click="exportAs('json')">导出 JSON</button><button class="secondary-button" :disabled="exporting" @click="exportAs('csv')">导出 CSV</button></div><p v-if="exportResult" class="ok-text">已导出：{{exportResult}}</p></section><RouterLink class="secondary-button" to="/history">返回任务记录</RouterLink></section></template>
