<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import TaskStepper from '../components/TaskStepper.vue';import TaskTimeline from '../components/TaskTimeline.vue';import {api,type ExecutionPlan,type Task,type TaskEvent} from '../services/api'
const route=useRoute(),router=useRouter(),task=ref<Task|null>(null),plan=ref<ExecutionPlan|null>(null),ack=ref(false),busy=ref(false),error=ref(''),events=ref<TaskEvent[]>([]);const active=computed(()=>plan.value?.operations.filter(o=>['move','copy'].includes(o.action))||[]);const root=computed(()=>active.value[0]?.target_path?.replace(/[\\/][^\\/]+[\\/][^\\/]+$/,'')||'无目标');let timer=0
async function poll(){if(!task.value)return;const batch=await api.events(task.value.id,events.value.at(-1)?.seq||0);events.value.push(...batch.items);task.value=await api.task(task.value.id)}
onMounted(async()=>{try{const id=String(route.params.id);task.value=await api.task(id);plan.value=await api.plan(id,String(route.query.plan||''));await poll();timer=window.setInterval(()=>poll().catch(e=>{error.value=String(e)}),1000)}catch(e){error.value=String(e)}})
onBeforeUnmount(()=>window.clearInterval(timer))
async function execute(){if(busy.value||!task.value||!plan.value||!ack.value)return;busy.value=true;error.value='';try{const current=await api.task(task.value.id);task.value=current;await api.approvePlan(current.id,current.revision,plan.value);await api.executePlan(current.id,current.revision,plan.value);task.value=await api.task(current.id);if(['COMPLETED','COMPLETED_WITH_ISSUES'].includes(task.value.status))await router.push(`/tasks/${task.value.id}/report`)}catch(e){error.value=String(e)}finally{busy.value=false}}
async function pause(){if(!task.value)return;try{task.value=await api.task(task.value.id);task.value=await api.pauseTask(task.value.id,task.value.revision)}catch(e){error.value=String(e)}}
</script>
<template><section class="page"><TaskStepper :current="4"/><p class="eyebrow">FINAL AUTHORIZATION</p><h1>确认并执行整理计划</h1><p class="lead">目标、冲突规则和 plan hash 已冻结；执行时不会覆盖已存在文件。</p><p v-if="error" class="notice danger-notice">{{error}}</p><div v-if="plan" class="run-layout"><section class="state-card"><h2>操作清单</h2><div v-for="op in plan.operations" :key="op.operation_id" class="operation-row"><span>{{op.action}}</span><code>{{op.source_path}}</code><b>→</b><code>{{op.target_path||'原地保留'}}</code></div><h2>持久检查点</h2><TaskTimeline :events="events"/></section><aside class="state-card"><h2>最终确认</h2><p>目标根：<code>{{root}}</code></p><p>可执行 {{active.length}} 项 · keep_both 不覆盖</p><p>hash：<code>{{plan.plan_hash}}</code></p><label class="ack"><input v-model="ack" type="checkbox"/> 我已核对目标与计划 hash</label><button class="primary-button" :disabled="!ack||busy" @click="execute">{{busy?'正在安全执行…':`批准并${task?.settings.operation_mode==='copy'?'复制':'移动'} ${active.length} 项`}}</button><button v-if="busy" class="secondary-button" @click="pause">在安全检查点暂停</button><p v-if="task?.status==='PAUSE_REQUESTED'" class="notice">暂停已请求；当前文件核验完成后停止。</p><p v-if="task?.status==='PAUSED'" class="notice">任务已暂停，未完成项仍保留在同一计划中。</p></aside></div><div v-else class="state-card">正在读取计划…</div></section></template>
