<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'; import {useRoute,useRouter} from 'vue-router'; import TaskStepper from '../components/TaskStepper.vue'; import TaxonomyTree from '../components/TaxonomyTree.vue'; import EvidenceDrawer from '../components/EvidenceDrawer.vue'; import {api,type ExecutionPlan,type FileDetail,type FileItem,type Task,type Taxonomy} from '../services/api'
const route=useRoute(),router=useRouter(),task=ref<Task|null>(null),files=ref<FileItem[]>([]),trees=ref<Taxonomy[]>([]),detail=ref<FileDetail|null>(null),query=ref(''),filter=ref('all'),selected=ref(new Set<string>()),allFiltered=ref(false),plan=ref<ExecutionPlan|null>(null),error=ref(''),busy=ref(false)
const total=ref(0),page=ref(0),pageSize=100;const visible=computed(()=>files.value); const executable=computed(()=>plan.value?.operations.filter(o=>['move','copy'].includes(o.action)).length||0);const pageCount=computed(()=>Math.max(1,Math.ceil(total.value/pageSize)))
function statusFilter(){return filter.value==='all'?'':filter.value}
async function loadFiles(){if(!task.value)return;const result=await api.files(task.value.id,pageSize,page.value*pageSize,query.value,statusFilter());files.value=result.items;total.value=result.total}
onMounted(async()=>{try{const id=String(route.params.id);[task.value,trees.value]=await Promise.all([api.task(id),api.taxonomies(id)]);await loadFiles()}catch(e){error.value=String(e)}})
let queryTimer=0;watch([query,filter],()=>{page.value=0;window.clearTimeout(queryTimer);queryTimer=window.setTimeout(()=>loadFiles().catch(e=>{error.value=String(e)}),150)})
async function inspect(f:FileItem){if(task.value)detail.value=await api.file(task.value.id,f.id)}
function selectPage(){selected.value=new Set(visible.value.map(f=>f.id));allFiltered.value=false} async function selectAll(){if(!task.value)return;busy.value=true;try{const ids:string[]=[];for(let offset=0;offset<total.value;offset+=500){const batch=await api.files(task.value.id,500,offset,query.value,statusFilter());ids.push(...batch.items.map(item=>item.id))}selected.value=new Set(ids);allFiltered.value=true}finally{busy.value=false}} function toggle(id:string){const next=new Set(selected.value);next.has(id)?next.delete(id):next.add(id);selected.value=next} function targetFor(id:string){return plan.value?.operations.find(o=>o.file_id===id)?.target_path||'原地保留'}
async function changePage(delta:number){page.value=Math.max(0,Math.min(pageCount.value-1,page.value+delta));await loadFiles()}
async function compile(){if(!task.value)return;if(task.value.settings.operation_mode==='report_only'){await router.push(`/tasks/${task.value.id}/report`);return}busy.value=true;try{plan.value=await api.compilePlan(task.value.id)}catch(e){error.value=String(e)}finally{busy.value=false}}
async function next(){if(!task.value||!plan.value)return;if(task.value.settings.operation_mode==='report_only')return router.push(`/tasks/${task.value.id}/report`);await router.push(`/tasks/${task.value.id}/run?plan=${plan.value.plan_id}&hash=${plan.value.plan_hash}`)}
</script>
<template><section class="page review-page"><TaskStepper :current="3"/><header class="page-heading"><div><p class="eyebrow">ARCHIVE REVIEW</p><h1>审阅归档方案</h1><p class="lead">原文件尚未改变；待确认项默认原地保留。</p></div><span class="mode-chip">{{task?.settings.operation_mode}}</span></header><p v-if="error" class="notice danger-notice">{{error}}</p><div class="review-toolbar"><button :class="{active:filter==='all'}" @click="filter='all'">全部 {{filter==='all'?total:''}}</button><button :class="{active:filter==='eligible'}" @click="filter='eligible'">可处理</button><button :class="{active:filter==='excluded'}" @click="filter='excluded'">已排除</button><input v-model="query" aria-label="搜索文件" placeholder="搜索文件或相对路径" @keydown.ctrl.f.prevent="($event.currentTarget as HTMLInputElement).focus()"/></div><div class="review-grid"><aside class="category-pane"><TaxonomyTree v-if="trees.find(x=>x.status==='approved')" :taxonomy="trees.find(x=>x.status==='approved')!"/></aside><section class="mapping-pane"><div class="selection-row"><button @click="selectPage">全选当前页（{{visible.length}}）</button><button :disabled="busy" @click="selectAll">全选筛选结果（{{total}}）</button><span>{{allFiltered?'全部筛选结果':'当前页'}}已选 {{selected.size}}</span></div><button v-for="f in visible" :key="f.id" class="mapping-row" @click="inspect(f)"><input type="checkbox" :checked="selected.has(f.id)" @click.stop="toggle(f.id)"/><span><b>{{f.basename}}</b><small :title="f.relative_path">{{f.relative_path}}</small></span><span class="path-arrow">→</span><span :title="targetFor(f.id)">{{plan?targetFor(f.id):(f.scan_status==='excluded'?'原地保留':'编译后显示确定目标')}}</span><em>{{f.scan_status}}</em></button><div v-if="!visible.length" class="state-card">没有符合当前筛选的文件。</div><nav class="selection-row" aria-label="文件分页"><button :disabled="page===0" @click="changePage(-1)">上一页</button><span>第 {{page+1}} / {{pageCount}} 页 · 共 {{total}} 项</span><button :disabled="page+1>=pageCount" @click="changePage(1)">下一页</button></nav></section><EvidenceDrawer :detail="detail" @close="detail=null"/></div><footer class="action-bar"><span>{{task?.settings.operation_mode==='report_only'?'只读任务 · 已执行 0 项':plan?`可执行 ${executable} 项 · 计划 ${plan.plan_hash.slice(0,10)}`:'尚未编译确定性计划'}}</span><button v-if="!plan" class="primary-button" :disabled="busy" @click="compile">{{task?.settings.operation_mode==='report_only'?'查看只读报告':'生成并核对最终计划'}}</button><button v-else class="primary-button" @click="next">继续确认 {{executable}} 项</button></footer></section></template>
